name: gdsc_ys_color
description: Color system for GDSC Yonsei & other chapters
version: 1.0.0
homepage: https://gdsc-ys.github.io/semantic-demo/
repository: https://github.com/gdsc-ys/color-flutter

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
